server.port: 8080
spring:
  profiles.active: local
  thymeleaf:
    prefix: classpath:/thymeleaf/
    mode: HTML
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    cache: false


serial:
  port: COM4
  baudrate: 9600
  databits: 8
  stopbits: 1
  parity: 0